# =============================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS (POSTGRESQL)
# =============================================================================

# Indica que usaremos el driver de PostgreSQL
quarkus.datasource.db-kind=postgresql

quarkus.datasource.jdbc.url=${QUARKUS_DATASOURCE_JDBC_URL}
quarkus.datasource.username=${QUARKUS_DATASOURCE_USERNAME}
quarkus.datasource.password=${QUARKUS_DATASOURCE_PASSWORD}

# "update" asegura que si agregas una columna en Java, se cree en Postgres automáticamente
quarkus.hibernate-orm.database.generation=update

# Muestra en la consola de Render las consultas SQL que se ejecutan (útil para debug)
quarkus.hibernate-orm.log.sql=true

# Habilitamos CORS para que React (en otra URL) pueda pedirle datos a Quarkus
quarkus.http.cors=true

# Permitimos que cualquier origen consulte (puedes cambiar '*' por la URL de tu frontend más adelante)
quarkus.http.cors.origins=*

# Métodos y headers permitidos para el formulario de contacto y carga de planes
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

# Puerto por defecto de Quarkus (8080)
quarkus.http.port=8080