# Configuración MySQL
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=Jmm1205*
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/godream_db

# Generación automática de tablas (solo para desarrollo)
quarkus.hibernate-orm.database.generation=update

# Habilitar CORS para conectar con React
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000,http://localhost:5173